fix: github action config updated

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -20,18 +20,37 @@ jobs:
 
       - name: Check CircleCI Build Status
         run: |
-          # Fetch the latest CircleCI build status using CircleCI API
-          CIRCLECI_STATUS=$(curl -s -u ${CIRCLECI_TOKEN}: \
-            "https://circleci.com/api/v2/project/github/<YOUR_GITHUB_USERNAME>/<YOUR_REPO_NAME>/pipeline?branch=trunk" | \
-            jq -r '.items[0].state')
+          # Loop to check CircleCI build status until it is complete
+          while : ; do
+            CIRCLECI_STATUS=$(curl -s -u ${CIRCLECI_TOKEN}: \
+              "https://circleci.com/api/v2/project/github/shield-auth/shield/pipeline?branch=trunk" | \
+              jq -r '.items[0].state')
 
-          # Check if the last build was successful
-          if [ "$CIRCLECI_STATUS" != "success" ]; then
-            echo "CircleCI build did not pass. Exiting."
-            exit 1
-          else
-            echo "CircleCI build passed. Proceeding with Docker build and push."
-          fi
+            # If status is running, wait and check again in 30 seconds
+            if [ "$CIRCLECI_STATUS" == "running" ]; then
+              echo "CircleCI build is still running. Waiting for 30 seconds..."
+              sleep 30
+              continue
+            fi
+
+            # If status is failed, exit
+            if [ "$CIRCLECI_STATUS" == "failed" ]; then
+              echo "CircleCI build failed. Exiting."
+              exit 1
+            fi
+
+            # If status is successful, proceed
+            if [ "$CIRCLECI_STATUS" == "success" ]; then
+              echo "CircleCI build passed. Proceeding with Docker build and push."
+              break
+            fi
+
+            # If status is unknown, exit
+            if [ -z "$CIRCLECI_STATUS" ]; then
+              echo "Unable to determine CircleCI build status. Exiting."
+              exit 1
+            fi
+          done
 
       - name: Build the project
         run: cargo build --verbose
